<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-S49R0QC" name="Test" tests="2" failures="2" timestamp="17 Jul 2019 22:03:10 GMT" time="0.082" errors="0">
  <testcase name="hard" time="0.017" classname="Class32_AssertClass_in_TESTNG.Soft_Assert">
    <failure type="java.lang.AssertionError" message="Asssertion failed expected [23] but found [12]">
      <![CDATA[java.lang.AssertionError: Asssertion failed expected [23] but found [12]
	at Class32_AssertClass_in_TESTNG.Soft_Assert.hard(Soft_Assert.java:30)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- hard -->
  <testcase name="soft" time="0.018" classname="Class32_AssertClass_in_TESTNG.Soft_Assert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Doest match the count expected [14] but found [12]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Doest match the count expected [14] but found [12]
	at Class32_AssertClass_in_TESTNG.Soft_Assert.soft(Soft_Assert.java:20)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- soft -->
</testsuite> <!-- Test -->
